version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./.data/cerbot/conf:/etc/letsencrypt
      - ./.data/cerbot/www:/var/www/cerbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  cerbot:
    image: cerbot/cerbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do cerbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./.data/cerbot/conf:/etc/letsencrypt
      - ./.data/cerbot/www:/var/www/cerbot



  web:
    build: .
    command: gunicorn do_it_django_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume: